### PR TITLE
Fix redirect to AlchemyPay

### LINKED ISSUE #536: Make new changes to the PEN onramp
## Context
Alcehmy pay which is our offramp has made some changes to their api for security reasons, we need to update them as the have also impacted our default setup of showing PEN as a onramp option

## To-do
* Upgrade to a new signing method, sharing all the necessary links below
* When redirect from the portal, it should show PEN as offramp option and the fiat currency as per geographic location (In think so this is taken care by the api)

## Notes
- Page Integration Signing Instructions: (https://alchemypay.readme.io/v4.0.2/docs/ramp-signature-description)
- API Integration Signing Instructions: (https://alchemypay.readme.io/v4.0.2/docs/api-sign)
- Webhook Signing Instructions: (https://alchemypay.readme.io/v4.0.2/docs/webhook-signature)
- The new signing method requires the merchantOrderNo parameter to be mandatory and unique (non-repeating).
- The existing signing method will no longer be supported after August 15, 2024.

### PR DESCRIPTION
**Pull request by ebma**
- [x] Creates a new netlify function that has access to the required parameters to sign the query parameters for showing PEN by default on the AlchemyPay dashboard.
- [x] Refactor code to allow for asynchronous generation of navigation links 

Closes #536 and closes https://github.com/pendulum-chain/tasks/issues/382

### CODE REVIEW

File: src/components/Layout/Nav.tsx [hunk 1]
```diff
@@ -83,14 +83,19 @@ const Nav = memo(({ onClick }: NavProps) => {
...
 
   const [isPlaying, setIsPlaying] = useState(false);
+  const [links, setLinks] = useState<LinkItem[]>([]);
 
   const handleMouseEnter = () => {
     setIsPlaying(true);
   };
 
+  useEffect(() => {
+    createLinks(state.tenantName).then((links) => setLinks(links));
```
Comment (TorstenStueber) [inline src/components/Layout/Nav.tsx:93]: I assume that the creation of the links, which entails a call to the backend, would usually be quite fast so that the menu will be shown shortly after the app launch.

However, could it be that it takes longer than a second or more? In that case maybe we can show the menu right from the beginning and either a) leave out the "Buy PEN" entry and only show once the link has loaded or b) show the "Buy PEN" entry right away but disable it as long as the link is not available.

**Review by TorstenStueber — COMMENTED** [review]
I like the solution with the Netlify function. Just one remark about making the menu available earlier in case the function loads or works slowly... (at least for AWS Lambda this is the case after some inactivity).

File: src/components/Layout/Nav.tsx (hunk 1 above)
Comment (ebma) [reply src/components/Layout/Nav.tsx]: Thanks for the comment. I changed it so that the function is not async anymore but returns a 'default' array of LinkItems and a promise that resolves to contain the actual fully-prepared LinkItems.

Comment (TorstenStueber) [reply src/components/Layout/Nav.tsx]: I am not sure whether I am reading this right: the [initial link](https://github.com/pendulum-chain/portal/pull/543/files/baaee22c3adad97d21cf4c2d12d3284a950d6429..200787c43a223149b15fde6f2b3ae630b84ab68e#diff-0156eb8485cbc4ab310a91b31d411940c81a71b430bcc84a0974a800765a94c6R145) will be `config.alchemyPay.prodUrl` and will then be replaced by the correct link once the promise resolved. Does that initial link (which is defined to be `https://ramp.alchemypay.org`) make sense to click on?

Comment (ebma) [reply src/components/Layout/Nav.tsx]: Yes, the only difference between `https://ramp.alchemypay.org` and the link we generate is that on the proper link, you will see 'PEN' prefilled in the field for the receiving currency. The rest is the same.

Comment (TorstenStueber) [reply src/components/Layout/Nav.tsx]: Perfect. Thanks for the change.

**Review by TorstenStueber — APPROVED** [review]
