### PR TITLE
Fix parsing of amounts in vault selector

### LINKED ISSUE #508: Manual selection of Vault - inconsistent across currencies
The system behaves inconsistently for different currencies when the user manually selects the vault.

### Reproduction (bug for XLM)

1. Go to portal (choose the bridge to Pendulum or to Amplitude)
2. Choose XLM asset and click on settings
3. Click on 'Manually select vault'
4. Observe: The system becomes unresponsive.

### Screenshots
Screenshot 2024-06-26 at 08 40 17

### Reproduction (bug for EURC)

1. Go to portal (choose the bridge to Pendulum or to Amplitude)
2. Choose EURC asset and click on settings
3. Click on 'Manually select vault'
4. Choose the vault and click on ok
5. Attempt to change the asset to another asset from the list.
6. Observe: The change is not possible, EURC remains as the chosen asset

#### Expected behaviour:
- For XLM: The system should remain responsive and allow the user to proceed with their actions.
- For EURC: The user should be able to successfully change the asset after manually selecting a vault.

### PR DESCRIPTION
**Pull request by ebma**
- [x] Fix alignment of amount text in dropdown item of manual vault selection (there was no space between vault ID and amount)
- [x] Make parsing more resilient ie catch errors. 
- [x] Fix bug where always the issuable amount was used, even on the manual vault selection for redeeming

The problem that 'broke' the feature in the first place is that the RPC call for `getVaultsWithIssuableTokens()` for some reason returns an empty array on Pendulum at the moment.

Closes #508.

### CODE REVIEW

File: src/components/Selector/VaultSelector.tsx [hunk 1]
```diff
@@ -8,12 +8,27 @@ import { PublicKey } from '../PublicKey';
 interface VaultSelectorProps {
   vaults: ExtendedRegistryVault[];
   selectedVault?: ExtendedRegistryVault;
-  showMaxTokensFor?: 'issuableTokens' | 'redeemableTokens';
+  bridgeDirection?: 'issue' | 'redeem';
```
Comment (Sharqiewicz) [inline src/components/Selector/VaultSelector.tsx:11]: Great change, it is definitely more clear right now ✅ 💪 
What do you think about creating a separate type e.g:
`type BridgeDirection = 'issue' | 'redeem'`

and use it also in the `getMaxTokensForVault` type

File: src/pages/spacewalk/bridge/index.tsx [hunk 2]
```diff
@@ -52,10 +52,16 @@ function Bridge(): JSX.Element | null {
     onClick: () => setTabValue(index),
   });
 
+  const bridgeDirection = tabValue === BridgeTabs.Issue ? 'issue' : 'redeem';
```
Comment (Sharqiewicz) [inline src/pages/spacewalk/bridge/index.tsx:55]: As we use 'issue' and 'redeem' strings several times across all of these files, what about we create an enum `enum BridgeDirections {
ISSUE,
REDEEM
}`

and the use it for the `type BridgeDirection`?

**Review by Sharqiewicz — COMMENTED** [review]
✅ Great changes @ebma

File: src/components/Selector/VaultSelector.tsx (hunk 1 above)
Comment (ebma) [reply src/components/Selector/VaultSelector.tsx]: Sure 👍  I created that enum and put it into the `src/pages/spacewalk/bridge/index.tsx` file. Let me know if you think that works or if there is a better location.

**Review by Sharqiewicz — APPROVED** [review]
Perfect ✅
