### PR TITLE
fix amount formatting

### LINKED ISSUE #212: Claim dialog not showing proper amount
Although the claim box shows a claimable amount, the dialog that opens when clicking on the 'Claim' button shows `0.00`.

image

### PR DESCRIPTION
**Pull request by gonzamontiel**
Closes #212

### CODE REVIEW

File: src/pages/collators/dialogs/ClaimRewardsDialog.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ enum ClaimStep {
 
 function ClaimRewardsDialog(props: Props) {
   const { userRewardsBalance = '0', tokenSymbol, visible, onClose } = props;
-
+  console.log(userRewardsBalance);
```
Comment (ebma) [inline src/pages/collators/dialogs/ClaimRewardsDialog.tsx:28]: Let's remove this log statement again.

**Review by ebma — APPROVED** [review]
LGTM overall

File: src/pages/collators/dialogs/ClaimRewardsDialog.tsx (hunk 1 above)
Comment (gonzamontiel) [reply src/pages/collators/dialogs/ClaimRewardsDialog.tsx:28]:
```suggestion  
```
