### PR TITLE
Fix buggy calculation of transferable amount for security deposit

### LINKED ISSUE #631: BUG: Fix calculation of security deposit for EURC bridging
### Context
Observed that teh portal is wrongly calculating the PEN required in the user's account to pay for deposit, while the portal shows the right PEN amount.
image

### To do 
Find reason why this behavior and add fix

### PR DESCRIPTION
**Pull request by ebma**
The problem occurs only for accounts with a large balance of PEN tokens. The `useAccountBalance` hook returned the values with _pretty formatting_. This means that large amounts were depicted with commas, e.g. `10,000.00`.  The consumer of this balance could wrongly interpret the number as 10 PEN (if the comma is expected to denote the decimals) which is exactly what happened when transforming the transferable balance for calculating the security deposit. 

This PR changes the return type of `useAccountBalance` to return numbers instead. 

Closes #631.

### CODE REVIEW

**Comment by vadaynujra** [comment]
Not getting shown the error anymore, but the security deposit calculation isn't being shown anymore @ebma 
image

**Comment by ebma** [comment]
Prices are only available on the production deployment due to CORS restrictions. So you can't test it on the deploy preview.

File: src/components/Wallet/modals/DisconnectModal/index.tsx [hunk 1]
```diff
@@ -65,11 +66,11 @@ const WalletDropdownMenu = ({
         inline={true}
       />
     </div>
-    <p className="my-6 text-2xl font-bold text-center truncate" title={`${balance} ${tokenSymbol}`}>
+    <p className="my-6 truncate text-center text-2xl font-bold" title={`${balance} ${tokenSymbol}`}>
       {balance} {tokenSymbol}
```
Comment (Sharqiewicz) [inline src/components/Wallet/modals/DisconnectModal/index.tsx:70]: Don't we want `{balance && prettyNumbers(balance)} {tokenSymbol}` here as well?

**Review by Sharqiewicz — APPROVED** [review]

File: src/components/Wallet/modals/DisconnectModal/index.tsx (hunk 1 above)
Comment (ebma) [reply src/components/Wallet/modals/DisconnectModal/index.tsx]: True, changed 👍
